### ISSUE TITLE
Error on cmd 'npm run export'

### ISSUE THREAD

**Issue by interstellarelf** [ialoig/nodejs-png2svg#1]
Found one error which is easy to correct. On my machine we run 'npm run export' and get the error of 'rleRow.split('#') is not a function'. This line of code is found in the decoder script. The error happens because rleRow is an array and not a string. By renaming rleRow to rleRowArray, and copying the characters of this array into a new string by name of 'rleRow' the output will then be correct since rleRow is now a string and now it has the string.split() function.

I made my edit inside the FOR loop of the function decode(). My FOR loop looks like this: 

let rects = []
	for (let row = 0; row < rleRows.length; row++) {
		const /*RENAMED to rleRowArray*/ rleRowArray = rleRows[row] // ex : #ffffff32#0000004#ffffff28

		//TEMP FIX
		var rleRow = '';

		if(rleRowArray instanceof Array)
		{
				for(var x = 0; x < rleRowArray.length; x++)
				{
					rleRow += rleRowArray[x];
				}
		}

		//END TEMP FIX

		const rectsPerRow = generateRects(row, rleRow)
		rects.push(rectsPerRow)
	}

Now, rleRow is a string and will work as expected.

**Comment by rohit-gh** [comment]
@interstellarelf solution looks great. Here's the rewrite file of his solution.
Go to scripts/decoder.js.  Replace the contents with : 
```
const chalk = require("chalk")


const decode = (rleRows) => {
  console.log(chalk.white("\nSTART decoding file ..."))

  const svgOpen = '<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">\n'
  const svgClose = "</svg>"

  let rects = []
  for (let row = 0; row < rleRows.length; row++) {
    const rleRowArray = rleRows[row] // ex : #ffffff32#0000004#ffffff28
    var rleRow = '';

    if (rleRowArray instanceof Array) {
      for (var x = 0; x < rleRowArray.length; x++) {
        rleRow += rleRowArray[x];
      }
    }


    const rectsPerRow = generateRects(row, rleRow)
    rects.push(rectsPerRow)
  }

  const svg = svgOpen + rects.join("") + svgClose
  return svg
}


const generateRects = (row, rlerow) => {
  if (rlerow.length === 0)
    return

  // split RLE row for the special char
  const rlePixel = rlerow.split("#") // ex: [ '', 'ffffff32', '0000004', 'ffffff28' ]

  if (rlePixel.length === 0)
    return

  let xWidth = 0 // variable to save x axis values; should be incremented by width
  let rects = [] // store all the generated rects

  const regHex = /([a-x\d]{6})/
  for (let i = 0; i < rlePixel.length; i++) {

    const pixel = rlePixel[i] // ex: ffffff64
    const pixelinfo = pixel?.split(regHex)
    if (pixelinfo.length === 3) {

      const fill = pixelinfo[1]
      const width = parseInt(pixelinfo[2])
      const info = {
        x: xWidth,
        y: row,
        width: width,
        fill: fill
      }

      const rect = getSVGRect(info)
      rects.push(rect)

      xWidth += width // update x axis value
    }
  }
  return rects
}


const getSVGRect = (info) => {
  // convert transparency tag into the correct svg value
  const fill = info.fill === "xxxxxx" ? "none" : "#" + info.fill
  const rect =
    '<rect x="' + info.x +
    '" y="' + info.y +
    '" width="' + info.width +
    '" height="1" shape-rendering="crispEdges"' +
    ' fill="' + fill + '"/>' + "\n"
  return rect

}


module.exports = {
  decode
}
```

**Comment by ialoig** [comment]
Hi @interstellarelf and thanks for reporting the issue.
It's now fixed.

Thanks again !
